// LOCALHOST
### Get all countries
GET http://localhost:3001/countries


### Get country by id
GET http://localhost:3001/countries/66089ab627ded2a76bd67059

//LINK RENDER
### Get all Countries
GET https://cse-341-project2-c9x7.onrender.com/countries

### Create Contry information
POST http://localhost:3001/countries HTTP/1.1
content-type: application/json

{
    "govWebSite": "https://www.governo.it/en  ",
    "countryName": "Italy",
    "OfficialName": "Italian Republic",
    "territorialExtension": "302,073 km²",
    "officialCurrency": "Euro",
    "flagColors":"red, green and white",
    "yearOfCreation":"1861 b.c."
}

### Put Country
PUT http://localhost:3001/countries/660450050d345acad75b8dfa HTTP/1.1
content-type: application/json

{
    "govWebSite": "https://www.austria.info/",
    "countryName": "Austria",
    "OfficialName": "Republic of Austria",
    "territorialExtension": "83,871 km²",
    "officialCurrency": "Euro",
    "flagColors":"red and white",
    "yearOfCreation":"07/27/1955"
}


### DELETE Contact
DELETE http://localhost:3001/countries/66044f22140b0d76d96d3a64 HTTP/1.1

