// LOCALHOST
### Get all countries
GET http://localhost:3001/countries


### Get country by id
GET http://localhost:3001/countries/66089ab627ded2a76bd67059

//LINK RENDER
### Get all Countries
GET https://cse-341-project2-c9x7.onrender.com/countries

### Create Contry information
POST http://localhost:3001/countries HTTP/1.1
content-type: application/json

{
    "govWebSite": "https://denmark.dk/",
    "countryName": "Denmark",
    "OfficialName": "Kingdom of Denmark",
    "territorialExtension": "42,921",
    "officialCurrency": "Danish Crown",
    "flagColors": "red and white",
    "yearOfCreation": "x century"
}

### Put Country
PUT http://localhost:3001/countries/660450050d345acad75b8dfa HTTP/1.1
content-type: application/json

{
    "govWebSite": "https://denmark.dk/",
    "countryName": "Denmark",
    "OfficialName": "Kingdom of Denmark",
    "territorialExtension": "42,921",
    "officialCurrency": "Danish Crown",
    "flagColors": "red and white",
    "yearOfCreation": "x century"

}


### DELETE Contact
DELETE http://localhost:3001/countries/660431e9773b53eb55705aa8 HTTP/1.1

