// LOCALHOST
### Get all countries
GET http://localhost:3001/countries


### Get country by id
GET http://localhost:3001/countries/65fd6aeaaecfd5f9e9155e25

//LINK RENDER
### Get all Countries
GET https://cse-341-project2-c9x7.onrender.com

### Create Contry information
POST http://localhost:3001/countries HTTP/1.1
content-type: application/json

{
    "govWebSite": "req.body.govwebsite",
    "countryName": "req.body.countryname",
    "OfficialName": "req.body.name",
    "territorialExtension": "req.body.territorialextension",
    "officialCurrency": "req.body.officialcurrency",
    "flagColors": "req.body.flagcolors",
    "yearOfCreation": "req.body.yearOfcreation"
}